// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_users.sql

package sqlc

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT user_id, username, email, password_hash, password_salt FROM app_users
WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, userID int64) (AppUser, error) {
	row := q.db.QueryRowContext(ctx, getUser, userID)
	var i AppUser
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.PasswordSalt,
	)
	return i, err
}
