// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlc

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (
	user_id, media_id,
	content, rating
) VALUES (
	?, ?,
	?, ?
)
RETURNING comment_id, user_id, media_id, content, rating, created_at
`

type CreateCommentParams struct {
	UserID  int64
	MediaID int64
	Content string
	Rating  int64
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.UserID,
		arg.MediaID,
		arg.Content,
		arg.Rating,
	)
	var i Comment
	err := row.Scan(
		&i.CommentID,
		&i.UserID,
		&i.MediaID,
		&i.Content,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments
WHERE comment_id = ?
`

func (q *Queries) DeleteComment(ctx context.Context, commentID int64) error {
	_, err := q.db.ExecContext(ctx, deleteComment, commentID)
	return err
}

const getComment = `-- name: GetComment :one
SELECT comment_id, user_id, media_id, content, rating, created_at FROM comments
WHERE comment_id = ? LIMIT 1
`

func (q *Queries) GetComment(ctx context.Context, commentID int64) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getComment, commentID)
	var i Comment
	err := row.Scan(
		&i.CommentID,
		&i.UserID,
		&i.MediaID,
		&i.Content,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT comment_id, user_id, media_id, content, rating, created_at FROM comments
`

func (q *Queries) ListComments(ctx context.Context) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, listComments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.CommentID,
			&i.UserID,
			&i.MediaID,
			&i.Content,
			&i.Rating,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
set user_id = ?,
media_id = ?,
content = ?,
rating = ?
WHERE comment_id = ?
RETURNING comment_id, user_id, media_id, content, rating, created_at
`

type UpdateCommentParams struct {
	UserID    int64
	MediaID   int64
	Content   string
	Rating    int64
	CommentID int64
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateComment,
		arg.UserID,
		arg.MediaID,
		arg.Content,
		arg.Rating,
		arg.CommentID,
	)
	var i Comment
	err := row.Scan(
		&i.CommentID,
		&i.UserID,
		&i.MediaID,
		&i.Content,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}
