// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: directors.sql

package sqlc

import (
	"context"
)

const createDirector = `-- name: CreateDirector :one
INSERT INTO directors (
	name, date_of_birth,
	date_of_death, biography
) VALUES (
	?, ?,
	?, ?
)
RETURNING director_id, name, date_of_birth, date_of_death, biography
`

type CreateDirectorParams struct {
	Name        string
	DateOfBirth *string
	DateOfDeath *string
	Biography   *string
}

func (q *Queries) CreateDirector(ctx context.Context, arg CreateDirectorParams) (Director, error) {
	row := q.db.QueryRowContext(ctx, createDirector,
		arg.Name,
		arg.DateOfBirth,
		arg.DateOfDeath,
		arg.Biography,
	)
	var i Director
	err := row.Scan(
		&i.DirectorID,
		&i.Name,
		&i.DateOfBirth,
		&i.DateOfDeath,
		&i.Biography,
	)
	return i, err
}

const deleteDirector = `-- name: DeleteDirector :exec
DELETE FROM directors
WHERE director_id = ?
`

func (q *Queries) DeleteDirector(ctx context.Context, directorID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDirector, directorID)
	return err
}

const getDirector = `-- name: GetDirector :one
SELECT director_id, name, date_of_birth, date_of_death, biography FROM directors
WHERE director_id = ? LIMIT 1
`

func (q *Queries) GetDirector(ctx context.Context, directorID int64) (Director, error) {
	row := q.db.QueryRowContext(ctx, getDirector, directorID)
	var i Director
	err := row.Scan(
		&i.DirectorID,
		&i.Name,
		&i.DateOfBirth,
		&i.DateOfDeath,
		&i.Biography,
	)
	return i, err
}

const listDirectors = `-- name: ListDirectors :many
SELECT director_id, name, date_of_birth, date_of_death, biography FROM directors
`

func (q *Queries) ListDirectors(ctx context.Context) ([]Director, error) {
	rows, err := q.db.QueryContext(ctx, listDirectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Director
	for rows.Next() {
		var i Director
		if err := rows.Scan(
			&i.DirectorID,
			&i.Name,
			&i.DateOfBirth,
			&i.DateOfDeath,
			&i.Biography,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDirector = `-- name: UpdateDirector :one
UPDATE directors
set name = ?,
date_of_birth = ?,
date_of_death = ?,
biography = ?
WHERE director_id = ?
RETURNING director_id, name, date_of_birth, date_of_death, biography
`

type UpdateDirectorParams struct {
	Name        string
	DateOfBirth *string
	DateOfDeath *string
	Biography   *string
	DirectorID  int64
}

func (q *Queries) UpdateDirector(ctx context.Context, arg UpdateDirectorParams) (Director, error) {
	row := q.db.QueryRowContext(ctx, updateDirector,
		arg.Name,
		arg.DateOfBirth,
		arg.DateOfDeath,
		arg.Biography,
		arg.DirectorID,
	)
	var i Director
	err := row.Scan(
		&i.DirectorID,
		&i.Name,
		&i.DateOfBirth,
		&i.DateOfDeath,
		&i.Biography,
	)
	return i, err
}
