// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package sqlc

import (
	"context"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (
	title, director_id,
	release_year, synopsis
) VALUES (
	?, ?,
	?, ?
)
RETURNING media_id, title, director_id, release_year, synopsis
`

type CreateMediaParams struct {
	Title       string
	DirectorID  int64
	ReleaseYear *int64
	Synopsis    *string
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.Title,
		arg.DirectorID,
		arg.ReleaseYear,
		arg.Synopsis,
	)
	var i Medium
	err := row.Scan(
		&i.MediaID,
		&i.Title,
		&i.DirectorID,
		&i.ReleaseYear,
		&i.Synopsis,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :exec
DELETE FROM media
WHERE media_id = ?
`

func (q *Queries) DeleteMedia(ctx context.Context, mediaID int64) error {
	_, err := q.db.ExecContext(ctx, deleteMedia, mediaID)
	return err
}

const getMedia = `-- name: GetMedia :one
SELECT media_id, title, director_id, release_year, synopsis FROM media
WHERE media_id = ? LIMIT 1
`

func (q *Queries) GetMedia(ctx context.Context, mediaID int64) (Medium, error) {
	row := q.db.QueryRowContext(ctx, getMedia, mediaID)
	var i Medium
	err := row.Scan(
		&i.MediaID,
		&i.Title,
		&i.DirectorID,
		&i.ReleaseYear,
		&i.Synopsis,
	)
	return i, err
}

const listMedia = `-- name: ListMedia :many
SELECT media_id, title, director_id, release_year, synopsis FROM media
`

func (q *Queries) ListMedia(ctx context.Context) ([]Medium, error) {
	rows, err := q.db.QueryContext(ctx, listMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Medium
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.MediaID,
			&i.Title,
			&i.DirectorID,
			&i.ReleaseYear,
			&i.Synopsis,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMedia = `-- name: UpdateMedia :one
UPDATE media
set title = ?,
director_id = ?,
release_year = ?,
synopsis = ?
WHERE media_id = ?
RETURNING media_id, title, director_id, release_year, synopsis
`

type UpdateMediaParams struct {
	Title       string
	DirectorID  int64
	ReleaseYear *int64
	Synopsis    *string
	MediaID     int64
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, updateMedia,
		arg.Title,
		arg.DirectorID,
		arg.ReleaseYear,
		arg.Synopsis,
		arg.MediaID,
	)
	var i Medium
	err := row.Scan(
		&i.MediaID,
		&i.Title,
		&i.DirectorID,
		&i.ReleaseYear,
		&i.Synopsis,
	)
	return i, err
}
