// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type AppUser struct {
	UserID       int64
	Username     string
	Email        sql.NullString
	PasswordHash string
	PasswordSalt string
}
