// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type AppUser struct {
	UserID       int64
	Username     string
	Email        *string
	PasswordHash string
	PasswordSalt string
}

type Comment struct {
	CommentID int64
	UserID    int64
	MediaID   int64
	Content   string
	Rating    int64
	CreatedAt time.Time
}

type Director struct {
	DirectorID  int64
	Name        string
	DateOfBirth *string
	DateOfDeath *string
	Biography   *string
}

type Medium struct {
	MediaID     int64
	Title       string
	DirectorID  int64
	ReleaseYear *int64
	Synopsis    *string
}
